/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_math.check" instead.
 */

#include <check.h>

#line 1 "s21_math.check"
#include <check.h>
#include <limits.h>
#include <math.h>
#include <stdlib.h>

#include "s21_math.h"

START_TEST(test_s21_abs_positive) {
#line 10
  int input1 = 3546385;
  int lib_result_1 = abs(input1);
  int our_result_1 = s21_abs(input1);
  ck_assert_int_eq(lib_result_1, our_result_1);
}
END_TEST

START_TEST(test_s21_abs_negative) {
#line 15
  int input2 = -1043934;
  int lib_result_2 = abs(input2);
  int our_result_2 = s21_abs(input2);
  ck_assert_int_eq(lib_result_2, our_result_2);
}
END_TEST

START_TEST(test_s21_abs_zero) {
#line 20
  int input4 = 0;
  int lib_result_4 = abs(input4);
  int our_result_4 = s21_abs(input4);
  ck_assert_int_eq(lib_result_4, our_result_4);
}
END_TEST

START_TEST(test_s21_abs_border) {
#line 25
  ck_assert_int_eq(s21_abs(5), abs(5));
}
END_TEST

START_TEST(test_s21_abs_border2) {
#line 27
  ck_assert_int_eq(s21_abs(-3), abs(-3));
}
END_TEST

START_TEST(test_s21_abs_border3) {
#line 29
  ck_assert_int_eq(s21_abs(0), abs(0));
}
END_TEST

START_TEST(test_s21_abs_border4) {
#line 31
  ck_assert_int_eq(s21_abs(-10), abs(-10));
}
END_TEST

START_TEST(test_s21_abs_border5) {
#line 33
  ck_assert_int_eq(s21_abs(1), abs(1));
}
END_TEST

START_TEST(test_s21_abs_border6) {
#line 35
  ck_assert_int_eq(s21_abs(2), abs(2));
}
END_TEST

START_TEST(test_s21_abs_border61) {
#line 37
  ck_assert_int_eq(s21_abs(3), abs(3));
}
END_TEST

START_TEST(test_s21_abs_border62) {
#line 39
  ck_assert_int_eq(s21_abs(-1), abs(-1));
}
END_TEST

START_TEST(test_s21_abs_border63) {
#line 41
  ck_assert_int_eq(s21_abs(-2), abs(-2));
}
END_TEST

START_TEST(test_s21_abs_border64) {
#line 43
  ck_assert_int_eq(s21_abs(-3), abs(-3));
}
END_TEST

START_TEST(test_s21_abs_border65) {
#line 45
  ck_assert_int_eq(s21_abs(100), abs(100));
}
END_TEST

START_TEST(test_s21_abs_border66) {
#line 47
  ck_assert_int_eq(s21_abs(-100), abs(-100));
}
END_TEST

START_TEST(test_s21_abs_border67) {
#line 49
  ck_assert_int_eq(s21_abs(40), abs(40));
}
END_TEST

START_TEST(test_s21_abs_border68) {
#line 51
  ck_assert_int_eq(s21_abs(INT_MAX), abs(INT_MAX));
}
END_TEST

START_TEST(test_s21_abs_border69) {
#line 53
  ck_assert_int_eq(s21_abs(INT_MIN), abs(INT_MIN));
}
END_TEST
START_TEST(test_s21_fabs_positive) {
#line 58
  double input5 = 3.14;
  double expected5 = fabs(input5);
  double result5 = s21_fabs(input5);
  ck_assert_ldouble_eq_tol(expected5, result5, 0.000001);
}
END_TEST

START_TEST(test_s21_fabs_negative) {
#line 63
  double input6 = -2.71828;
  double expected6 = fabs(input6);
  double result6 = s21_fabs(input6);
  ck_assert_ldouble_eq_tol(expected6, result6, 0.000001);
}
END_TEST

START_TEST(test_s21_fabs_zero) {
#line 68
  double input31 = 0.0;
  double expected31 = fabs(input31);
  double result31 = s21_fabs(input31);
  ck_assert_ldouble_eq_tol(expected31, result31, 0.000001);
}
END_TEST

START_TEST(test_s21_fabs_zero_minus) {
#line 73
  double input32 = S21_ZERO_MINUS;
  double expected32 = fabs(input32);
  double result32 = s21_fabs(input32);
  ck_assert_ldouble_eq_tol(expected32, result32, 0.000001);
}
END_TEST

START_TEST(test_s21_fabs_inf_minus) {
#line 78
  ck_assert_ldouble_infinite(s21_fabs(S21_INFINITE_MINUS));
  ck_assert_ldouble_gt(s21_fabs(S21_INFINITE_MINUS), 0);
}
END_TEST

START_TEST(test_s21_fabs_inf_plus) {
#line 81
  ck_assert_ldouble_infinite(s21_fabs(S21_INFINITE));
  ck_assert_ldouble_gt(s21_fabs(S21_INFINITE), 0);
}
END_TEST

START_TEST(test_s21_fabs_max_positive) {
#line 84
  double input7 = DBL_MAX;
  double expected7 = fabs(input7);
  double result7 = s21_fabs(input7);
  ck_assert_ldouble_eq_tol(expected7, result7, 0.000001);
}
END_TEST

START_TEST(test_s21_fabs_max_negative) {
#line 89
  double input8 = -DBL_MAX;
  double expected8 = fabs(input8);
  double result8 = s21_fabs(input8);
  ck_assert_ldouble_eq_tol(expected8, result8, 0.000001);
}
END_TEST

START_TEST(test_s21_fabs_min_positive) {
#line 94
  double input9 = DBL_MIN;
  double expected9 = fabs(input9);
  double result9 = s21_fabs(input9);
  ck_assert_ldouble_eq_tol(expected9, result9, 0.000001);
}
END_TEST

START_TEST(test_s21_fabs_min_negative) {
#line 99
  double input10 = -DBL_MIN;
  double expected10 = fabs(input10);
  double result10 = s21_fabs(input10);
  ck_assert_ldouble_eq_tol(expected10, result10, 0.000001);
}
END_TEST

START_TEST(test_s21_fabs_border) {
#line 104
  ck_assert_ldouble_eq_tol(s21_fabs(5.0), fabs(5.0), 0.000001);
}
END_TEST

START_TEST(test_s21_fabs_border2) {
#line 106
  ck_assert_ldouble_eq_tol(s21_fabs(-3.5), fabs(-3.5), 0.000001);
}
END_TEST

START_TEST(test_s21_fabs_border3) {
#line 108
  ck_assert_ldouble_eq_tol(s21_fabs(0.0), fabs(0.0), 0.000001);
}
END_TEST

START_TEST(test_s21_fabs_border4) {
#line 110
  ck_assert_ldouble_eq_tol(s21_fabs(-10.2), fabs(-10.2), 0.000001);
}
END_TEST

START_TEST(test_s21_fabs_border5) {
#line 112
  ck_assert_ldouble_eq_tol(s21_fabs(DBL_MAX), fabs(DBL_MAX), 0.000001);
}
END_TEST

START_TEST(test_s21_fabs_border6) {
#line 114
  ck_assert_ldouble_eq_tol(s21_fabs(DBL_MIN), fabs(DBL_MIN), 0.000001);
}
END_TEST

START_TEST(test_s21_fabs_border7) {
#line 116
  ck_assert_ldouble_eq_tol(s21_fabs(-DBL_MAX), fabs(-DBL_MAX), 0.000001);
}
END_TEST

START_TEST(test_s21_fabs_border8) {
#line 118
  ck_assert_ldouble_eq_tol(s21_fabs(-DBL_MIN), fabs(-DBL_MIN), 0.000001);
}
END_TEST

START_TEST(test_s21_fabs_border9) {
#line 120
  ck_assert_ldouble_nan(s21_fabs(S21_NAN));
  ck_assert_ldouble_nan(fabs(S21_NAN));
}
END_TEST
START_TEST(test_s21_acos_positive) {
#line 126
  double input11 = 0.7;
  double expected11 = acos(input11);
  double result11 = s21_acos(input11);
  ck_assert_ldouble_eq_tol(expected11, result11, 0.000001);
}
END_TEST

START_TEST(test_s21_acos_negative) {
#line 131
  double input12 = -0.5;
  double expected12 = acos(input12);
  double result12 = s21_acos(input12);
  ck_assert_ldouble_eq_tol(expected12, result12, 0.000001);
}
END_TEST

START_TEST(test_s21_acos_border) {
#line 136
  double input13 = 1.0;
  double expected13 = acos(input13);
  double result13 = s21_acos(input13);
  ck_assert_ldouble_eq_tol(expected13, result13, 0.000001);
}
END_TEST

START_TEST(test_s21_acos_border2) {
#line 141
  double input14 = 1.0;
  double expected14 = acos(input14);
  double result14 = s21_acos(input14);
  ck_assert_ldouble_eq_tol(expected14, result14, 0.000001);
}
END_TEST

START_TEST(test_s21_acos_border3) {
#line 146
  double input15 = -1.0;
  double expected15 = acos(input15);
  double result15 = s21_acos(input15);
  ck_assert_ldouble_eq_tol(expected15, result15, 0.000001);
}
END_TEST

START_TEST(test_s21_acos_border4) {
#line 151
  double input16 = 1.0 - 0.000001;
  double expected16 = acos(input16);
  double result16 = s21_acos(input16);
  ck_assert_ldouble_eq_tol(expected16, result16, 0.000001);
}
END_TEST

START_TEST(test_s21_acos_border5) {
#line 156
  double input17 = -1.0 + 0.000001;
  double expected17 = acos(input17);
  double result17 = s21_acos(input17);
  ck_assert_ldouble_eq_tol(expected17, result17, 0.000001);
}
END_TEST

START_TEST(test_s21_acos_border6) {
#line 161
  ck_assert_ldouble_eq_tol(s21_acos(0.5), acos(0.5), 0.000001);
}
END_TEST

START_TEST(test_s21_acos_border7) {
#line 163
  ck_assert_ldouble_eq_tol(s21_acos(0.0), acos(0.0), 0.000001);
}
END_TEST

START_TEST(test_s21_acos_border8) {
#line 165
  ck_assert_ldouble_eq_tol(s21_acos(-0.3), acos(-0.3), 0.000001);
}
END_TEST

START_TEST(test_s21_acos_border9) {
#line 167
  ck_assert_ldouble_eq_tol(s21_acos(0.8), acos(0.8), 0.000001);
}
END_TEST

START_TEST(test_s21_acos_border10) {
#line 169
  ck_assert_ldouble_eq_tol(s21_acos(1.0), acos(1.0), 0.000001);
}
END_TEST

START_TEST(test_s21_acos_border11) {
#line 171
  ck_assert_ldouble_eq_tol(s21_acos(-1.0), acos(-1.0), 0.000001);
}
END_TEST

START_TEST(test_s21_acos_border12) {
#line 173
  ck_assert_ldouble_nan(s21_acos(1.5));
  ck_assert_ldouble_nan(acos(1.5));
}
END_TEST

START_TEST(test_s21_acos_border13) {
#line 176
  ck_assert_ldouble_nan(s21_acos(-1.5));
  ck_assert_ldouble_nan(acos(-1.5));
}
END_TEST

START_TEST(test_s21_acos_border14) {
#line 179
  ck_assert_ldouble_nan(s21_acos(S21_NAN));
  ck_assert_ldouble_nan(acos(S21_NAN));
}
END_TEST

START_TEST(test_s21_acos_border110) {
#line 182
  ck_assert_ldouble_nan(s21_acos(-10.0));
  ck_assert_ldouble_nan(acos(-10.0));
}
END_TEST

START_TEST(test_s21_acos_border111) {
#line 185
  ck_assert_ldouble_eq_tol(s21_acos(-0.42), acos(-0.42), 0.000001);
}
END_TEST

START_TEST(test_s21_acos_border112) {
#line 187
  ck_assert_ldouble_eq_tol(s21_acos(0.42), acos(0.42), 0.000001);
}
END_TEST

START_TEST(test_s21_acos_border113) {
#line 189
  ck_assert_ldouble_eq_tol(s21_acos(0.424145), acos(0.424145), 0.000001);
}
END_TEST
START_TEST(test_s21_asin_positive) {
#line 194
  double input18 = 0.5;
  double expected18 = asin(input18);
  double result18 = s21_asin(input18);
  ck_assert_ldouble_eq_tol(expected18, result18, 0.000001);
}
END_TEST

START_TEST(test_s21_asin_negative) {
#line 199
  double input19 = -0.7;
  double expected19 = asin(input19);
  double result19 = s21_asin(input19);
  ck_assert_double_eq_tol(expected19, result19, 0.000001);
}
END_TEST

START_TEST(test_s21_asin_bound) {
#line 204
  double input20 = 1.0;
  double expected20 = asin(input20);
  double result20 = s21_asin(input20);
  ck_assert_double_eq_tol(expected20, result20, 0.000001);
}
END_TEST

START_TEST(test_s21_asin_bound2) {
#line 209
  ck_assert_ldouble_eq_tol(s21_asin(0.5), asin(0.5), 0.000001);
}
END_TEST

START_TEST(test_s21_asin_bound3) {
#line 211
  ck_assert_ldouble_eq_tol(s21_asin(0.0), asin(0.0), 0.000001);
}
END_TEST

START_TEST(test_s21_asin_bound4) {
#line 213
  ck_assert_ldouble_eq_tol(s21_asin(-0.3), asin(-0.3), 0.000001);
}
END_TEST

START_TEST(test_s21_asin_bound5) {
#line 215
  ck_assert_ldouble_eq_tol(s21_asin(0.8), asin(0.8), 0.000001);
}
END_TEST

START_TEST(test_s21_asin_bound6) {
#line 217
  ck_assert_ldouble_eq_tol(s21_asin(1.0), asin(1.0), 0.000001);
}
END_TEST

START_TEST(test_s21_asin_bound7) {
#line 219
  ck_assert_ldouble_eq_tol(s21_asin(-1.0), asin(-1.0), 0.000001);
}
END_TEST

START_TEST(test_s21_asin_bound8) {
#line 221
  ck_assert_ldouble_eq_tol(s21_asin(S21_ZERO_PLUS), asin(S21_ZERO_PLUS),
                           0.000001);
}
END_TEST

START_TEST(test_s21_asin_bound9) {
#line 223
  ck_assert_ldouble_eq_tol(s21_asin(S21_ZERO_MINUS), asin(S21_ZERO_MINUS),
                           0.000001);
}
END_TEST

START_TEST(test_s21_asin_bound10) {
#line 225
  ck_assert_ldouble_nan(s21_asin(S21_NAN));
  ck_assert_ldouble_nan(asin(S21_NAN));
}
END_TEST

START_TEST(test_s21_asin_bound11) {
#line 228
  ck_assert_ldouble_nan(s21_asin(1.5));
  ck_assert_ldouble_nan(asin(1.5));
}
END_TEST

START_TEST(test_s21_asin_bound12) {
#line 231
  ck_assert_ldouble_nan(s21_asin(-1.5));
  ck_assert_ldouble_nan(asin(-1.5));
}
END_TEST
START_TEST(test_s21_atan_positive) {
#line 237
  ck_assert_ldouble_eq_tol(s21_atan(0.5), atan(0.5), 0.000001);
}
END_TEST

START_TEST(test_s21_atan_zero) {
#line 239
  ck_assert_ldouble_eq_tol(s21_atan(0.0), atan(0.0), 0.000001);
}
END_TEST

START_TEST(test_s21_atan_zero_minus) {
#line 241
  ck_assert_ldouble_eq_tol(s21_atan(S21_ZERO_MINUS), atan(S21_ZERO_MINUS),
                           0.000001);
}
END_TEST

START_TEST(test_s21_atan_negative) {
#line 243
  ck_assert_ldouble_eq_tol(s21_atan(-0.3), atan(-0.3), 0.000001);
}
END_TEST

START_TEST(test_s21_atan_positive2) {
#line 245
  ck_assert_ldouble_eq_tol(s21_atan(0.8), atan(0.8), 0.000001);
}
END_TEST

START_TEST(test_s21_atan_border) {
#line 247
  ck_assert_ldouble_eq_tol(s21_atan(1.0), atan(1.0), 0.000001);
}
END_TEST

START_TEST(test_s21_atan_border2) {
#line 249
  ck_assert_ldouble_eq_tol(s21_atan(-1.0), atan(-1.0), 0.000001);
}
END_TEST

START_TEST(test_s21_atan_border3) {
#line 251
  ck_assert_ldouble_eq_tol(s21_atan(S21_INFINITE_MINUS),
                           atan(S21_INFINITE_MINUS), 0.000001);
}
END_TEST

START_TEST(test_s21_atan_border4) {
#line 253
  ck_assert_ldouble_eq_tol(s21_atan(S21_INFINITE), atan(S21_INFINITE),
                           0.000001);
}
END_TEST

START_TEST(test_s21_atan_border5) {
#line 255
  ck_assert_ldouble_nan(s21_atan(S21_NAN));
  ck_assert_ldouble_nan(atan(S21_NAN));
}
END_TEST

START_TEST(test_s21_atan_border6) {
#line 258
  ck_assert_ldouble_eq_tol(s21_atan(-1.9), atan(-1.9), 0.000001);
}
END_TEST

START_TEST(test_s21_atan_border7) {
#line 260
  ck_assert_ldouble_eq_tol(s21_atan(234.946), atan(234.946), 0.000001);
}
END_TEST
START_TEST(test_s21_ceil_positive) {
#line 267
  ck_assert_double_eq(s21_ceil(3.5), ceil(3.5));
}
END_TEST

START_TEST(test_s21_ceil_negative) {
#line 269
  ck_assert_double_eq(s21_ceil(-3.5), ceil(-3.5));
}
END_TEST

START_TEST(test_s21_ceil_zero) {
#line 271
  ck_assert_double_eq(s21_ceil(0.0), ceil(0.0));
}
END_TEST

START_TEST(test_s21_ceil_1) {
#line 273
  ck_assert_double_eq(s21_ceil(S21_ZERO_MINUS), ceil(S21_ZERO_MINUS));
}
END_TEST

START_TEST(test_s21_ceil_2) {
#line 275
  ck_assert_double_eq(s21_ceil(S21_INFINITE_MINUS), ceil(S21_INFINITE_MINUS));
}
END_TEST

START_TEST(test_s21_ceil_3) {
#line 277
  ck_assert_double_eq(s21_ceil(S21_INFINITE), ceil(S21_INFINITE));
}
END_TEST

START_TEST(test_s21_ceil_4) {
#line 279
  ck_assert_ldouble_nan(s21_ceil(S21_NAN));
  ck_assert_ldouble_nan(ceil(S21_NAN));
}
END_TEST

START_TEST(test_s21_ceil_5) {
#line 282
  ck_assert_double_eq(s21_ceil(DBL_MIN), ceil(DBL_MIN));
}
END_TEST

START_TEST(test_s21_ceil_6) {
#line 284
  ck_assert_double_eq(s21_ceil(DBL_MAX), ceil(DBL_MAX));
}
END_TEST

START_TEST(test_s21_ceil_7) {
#line 286
  ck_assert_double_eq(s21_ceil(-DBL_MAX), ceil(-DBL_MAX));
}
END_TEST

START_TEST(test_s21_ceil_8) {
#line 288
  ck_assert_double_eq(s21_ceil(-10), ceil(-10));
}
END_TEST

START_TEST(test_s21_ceil_9) {
#line 290
  ck_assert_double_eq(s21_ceil(-10.2), ceil(-10.2));
}
END_TEST

START_TEST(test_s21_ceil_10) {
#line 292
  ck_assert_double_eq(s21_ceil(10), ceil(10));
}
END_TEST

START_TEST(test_s21_ceil_11) {
#line 294
  ck_assert_double_eq(s21_ceil(10.2421), ceil(10.2421));
}
END_TEST

START_TEST(test_s21_ceil_12) {
#line 296
  ck_assert_double_eq(s21_ceil(0.4534), ceil(0.4534));
}
END_TEST

START_TEST(test_s21_ceil_13) {
#line 298
  ck_assert_double_eq(s21_ceil(-0.4534), ceil(-0.4534));
}
END_TEST

START_TEST(test_s21_ceil_14) {
#line 300
  ck_assert_double_eq(s21_ceil(-852954485022150971354.4534),
                      ceil(-852954485022150971354.4534));
}
END_TEST

START_TEST(test_s21_ceil_15) {
#line 302
  ck_assert_double_eq(s21_ceil(852954485022150971354.4534),
                      ceil(852954485022150971354.4534));
}
END_TEST
START_TEST(test_s21_cos_zero) {
#line 307
  ck_assert_ldouble_eq_tol(s21_cos(0.0), cos(0.0), 0.000001);
}
END_TEST

START_TEST(test_s21_cos_positive) {
#line 309
  ck_assert_ldouble_eq_tol(s21_cos(1.0), cos(1.0), 0.000001);
}
END_TEST

START_TEST(test_s21_cos_negative) {
#line 311
  ck_assert_ldouble_eq_tol(s21_cos(-1.0), cos(-1.0), 0.000001);
}
END_TEST

START_TEST(test_s21_cos_pi) {
#line 313
  ck_assert_ldouble_eq_tol(s21_cos(3.1415926), cos(3.1415926), 0.000001);
}
END_TEST

START_TEST(test_s21_cos_1) {
#line 315
  ck_assert_ldouble_eq_tol(s21_cos(S21_ZERO_PLUS), cos(S21_ZERO_PLUS),
                           0.000001);
}
END_TEST

START_TEST(test_s21_cos_2) {
#line 317
  ck_assert_ldouble_eq_tol(s21_cos(S21_ZERO_MINUS), cos(S21_ZERO_MINUS),
                           0.000001);
}
END_TEST

START_TEST(test_s21_cos_3) {
#line 319
  ck_assert_ldouble_nan(s21_cos(S21_INFINITE_MINUS));
  ck_assert_ldouble_nan(cos(S21_INFINITE_MINUS));
}
END_TEST

START_TEST(test_s21_cos_4) {
#line 322
  ck_assert_ldouble_nan(s21_cos(S21_INFINITE));
  ck_assert_ldouble_nan(cos(S21_INFINITE));
}
END_TEST

START_TEST(test_s21_cos_5) {
#line 325
  ck_assert_ldouble_nan(s21_cos(S21_NAN));
  ck_assert_ldouble_nan(cos(S21_NAN));
}
END_TEST
START_TEST(test_s21_exp_1) {
#line 332
  double x = 24.67;
  ck_assert_ldouble_eq_tol(exp(x), s21_exp(x), 0.000001);
}
END_TEST

START_TEST(test_s21_exp_2) {
#line 335
  double x = DBL_MAX;
  ck_assert_ldouble_eq(exp(x), s21_exp(x));
}
END_TEST

START_TEST(test_s21_exp_3) {
#line 338
  double x = DBL_MIN;
  ck_assert_ldouble_eq_tol(exp(x), s21_exp(x), 0.000001);
}
END_TEST

START_TEST(test_s21_exp_4) {
#line 341
  double x = 7.345e-29;
  ck_assert_ldouble_eq_tol(exp(x), s21_exp(x), 0.000001);
}
END_TEST

START_TEST(test_s21_exp_5) {
#line 344
  double x = -0.358;
  ck_assert_ldouble_eq_tol(exp(x), s21_exp(x), 0.000001);
}
END_TEST

START_TEST(test_s21_exp_neg) {
#line 347
  double x = -15.998;
  ck_assert_ldouble_eq_tol(exp(x), s21_exp(x), 0.000001);
}
END_TEST

START_TEST(test_s21_exp_zero) {
#line 350
  double x = 0.0;
  ck_assert_ldouble_eq_tol(exp(x), s21_exp(x), 0.000001);
}
END_TEST

START_TEST(test_s21_exp_1_1) {
#line 353
  ck_assert_ldouble_eq_tol(exp(S21_ZERO_MINUS), s21_exp(S21_ZERO_MINUS),
                           0.000001);
}
END_TEST

START_TEST(test_s21_exp_2_2) {
#line 355
  ck_assert_ldouble_eq_tol(exp(S21_ZERO_PLUS), s21_exp(S21_ZERO_PLUS),
                           0.000001);
}
END_TEST

START_TEST(test_s21_exp_3_3) {
#line 357
  ck_assert_ldouble_eq_tol(exp(S21_INFINITE_MINUS), s21_exp(S21_INFINITE_MINUS),
                           0.000001);
}
END_TEST

START_TEST(test_s21_exp_4_4) {
#line 359
  ck_assert_ldouble_infinite(exp(S21_INFINITE));
  ck_assert_ldouble_infinite(s21_exp(S21_INFINITE));
  ck_assert_ldouble_gt(exp(S21_INFINITE), 0);
  ck_assert_ldouble_gt(s21_exp(S21_INFINITE), 0);
}
END_TEST

START_TEST(test_s21_exp_5_5) {
#line 364
  ck_assert_ldouble_nan(s21_exp(S21_NAN));
  ck_assert_ldouble_nan(exp(S21_NAN));
}
END_TEST

START_TEST(test_s21_exp_3_10) {
#line 367
  double x = DBL_MAX;
  ck_assert_ldouble_eq(exp(x), s21_exp(x));
}
END_TEST

START_TEST(test_s21_exp_3_11) {
#line 370
  ck_assert_ldouble_eq_tol(exp(S21_INFINITE_MINUS), s21_exp(S21_INFINITE_MINUS),
                           0.000001);
}
END_TEST
START_TEST(test_s21_floor1) {
#line 375
  double x = 1.0;
  ck_assert_ldouble_eq_tol(s21_floor(x), floor(x), 0.000001);
}
END_TEST

START_TEST(test_s21_floor2) {
#line 378
  double x = 0.0;
  ck_assert_ldouble_eq_tol(s21_floor(x), floor(x), 0.000001);
}
END_TEST

START_TEST(test_s21_floor3) {
#line 381
  double x = -3.7;
  ck_assert_ldouble_eq_tol(s21_floor(x), floor(x), 0.000001);
}
END_TEST

START_TEST(test_s21_floor4) {
#line 384
  double x = 5.733857204968845;
  ck_assert_ldouble_eq_tol(s21_floor(x), floor(x), 0.000001);
}
END_TEST

START_TEST(test_s21_floor5) {
#line 387
  double x = 4575383848585776.5;
  ck_assert_ldouble_eq_tol(s21_floor(x), floor(x), 0.000001);
}
END_TEST

START_TEST(test_s21_floor6) {
#line 390
  double x = -4.365847373759706;
  ck_assert_ldouble_eq_tol(s21_floor(x), floor(x), 0.000001);
}
END_TEST

START_TEST(test_s21_floor7) {
#line 393
  double x = -4732323456789076.5;
  ck_assert_ldouble_eq_tol(s21_floor(x), floor(x), 0.000001);
}
END_TEST

START_TEST(test_s21_floor_1) {
#line 396
  ck_assert_ldouble_infinite(s21_floor(S21_INFINITE));
  ck_assert_ldouble_infinite(floor(S21_INFINITE));
  ck_assert_ldouble_gt(s21_floor(S21_INFINITE), 0);
  ck_assert_ldouble_gt(floor(S21_INFINITE), 0);
}
END_TEST

START_TEST(test_s21_floor_2) {
#line 401
  ck_assert_ldouble_infinite(s21_floor(S21_INFINITE_MINUS));
  ck_assert_ldouble_infinite(floor(S21_INFINITE_MINUS));
  ck_assert_ldouble_lt(s21_floor(S21_INFINITE_MINUS), 0);
  ck_assert_ldouble_lt(floor(S21_INFINITE_MINUS), 0);
}
END_TEST

START_TEST(test_s21_floor_3) {
#line 406
  ck_assert_ldouble_eq_tol(s21_floor(S21_ZERO_PLUS), floor(S21_ZERO_PLUS),
                           0.000001);
}
END_TEST

START_TEST(test_s21_floor_4) {
#line 408
  ck_assert_ldouble_eq_tol(s21_floor(S21_ZERO_MINUS), floor(S21_ZERO_MINUS),
                           0.000001);
}
END_TEST

START_TEST(test_s21_floor_5) {
#line 410
  ck_assert_ldouble_nan(s21_floor(S21_NAN));
  ck_assert_ldouble_nan(floor(S21_NAN));
}
END_TEST

START_TEST(test_s21_floor70) {
#line 413
  double x = DBL_MAX;
  ck_assert_ldouble_eq_tol(s21_floor(x), floor(x), 0.000001);
}
END_TEST

START_TEST(test_s21_floor71) {
#line 416
  double x = -DBL_MAX;
  ck_assert_ldouble_eq_tol(s21_floor(x), floor(x), 0.000001);
}
END_TEST

START_TEST(test_s21_floor72) {
#line 419
  double x = DBL_MIN;
  ck_assert_ldouble_eq_tol(s21_floor(x), floor(x), 0.000001);
}
END_TEST

START_TEST(test_s21_floor73) {
#line 422
  double x = -DBL_MIN;
  ck_assert_ldouble_eq_tol(s21_floor(x), floor(x), 0.000001);
}
END_TEST

START_TEST(test_s21_floor74) {
#line 425
  double x = 12345678901234;
  ck_assert_ldouble_eq_tol(s21_floor(x), floor(x), 0.000001);
}
END_TEST

START_TEST(test_s21_floor75) {
#line 428
  double x = 123456789012345;
  ck_assert_ldouble_eq_tol(s21_floor(x), floor(x), 0.000001);
}
END_TEST

START_TEST(test_s21_floor76) {
#line 431
  double x = 1234567890123456;
  ck_assert_ldouble_eq_tol(s21_floor(x), floor(x), 0.000001);
}
END_TEST

START_TEST(test_s21_floor77) {
#line 434
  double x = 12345678901234567;
  ck_assert_ldouble_eq_tol(s21_floor(x), floor(x), 0.000001);
}
END_TEST

START_TEST(test_s21_floor78) {
#line 437
  double x = 123456789012345678;
  ck_assert_ldouble_eq_tol(s21_floor(x), floor(x), 0.000001);
}
END_TEST

START_TEST(test_s21_floor79) {
#line 440
  double x = 1234567890123456789;
  ck_assert_ldouble_eq_tol(s21_floor(x), floor(x), 0.000001);
}
END_TEST
START_TEST(test_s21_fmod1) {
#line 447
  ck_assert_ldouble_eq_tol(fmod(-13.21313, 2.5), s21_fmod(-13.21313, 2.5),
                           0.000001);
}
END_TEST

START_TEST(test_s21_fmod2) {
#line 449
  ck_assert_ldouble_eq_tol(fmod(13.21313, 2.5), s21_fmod(13.21313, 2.5),
                           0.000001);
}
END_TEST

START_TEST(test_s21_fmod3) {
#line 451
  ck_assert_ldouble_eq_tol(fmod(-1000.21313, 2.5), s21_fmod(-1000.21313, 2.5),
                           0.000001);
}
END_TEST

START_TEST(test_s21_fmod4) {
#line 453
  ck_assert_ldouble_eq_tol(fmod(32346234.21313, 2.5),
                           s21_fmod(32346234.21313, 2.5), 0.000001);
}
END_TEST

START_TEST(test_s21_fmod5) {
#line 455
  ck_assert_ldouble_eq_tol(fmod(0, 2.5), s21_fmod(0, 2.5), 0.000001);
}
END_TEST

START_TEST(test_s21_fmod6) {
#line 457
  ck_assert_ldouble_eq_tol(fmod(2.5, 2.5), s21_fmod(2.5, 2.5), 0.000001);
}
END_TEST

START_TEST(test_s21_fmod_1) {
#line 459
  ck_assert_ldouble_eq_tol(fmod(S21_ZERO_PLUS, 2.5),
                           s21_fmod(S21_ZERO_PLUS, 2.5), 0.000001);
}
END_TEST

START_TEST(test_s21_fmod_2) {
#line 461
  ck_assert_ldouble_eq_tol(fmod(S21_ZERO_MINUS, 2.5),
                           s21_fmod(S21_ZERO_MINUS, 2.5), 0.000001);
}
END_TEST

START_TEST(test_s21_fmod_3) {
#line 463
  ck_assert_ldouble_nan(s21_fmod(S21_INFINITE_MINUS, 2.5));
  ck_assert_ldouble_nan(fmod(S21_INFINITE_MINUS, 2.5));
}
END_TEST

START_TEST(test_s21_fmod_4) {
#line 466
  ck_assert_ldouble_nan(s21_fmod(S21_INFINITE, 2.5));
  ck_assert_ldouble_nan(fmod(S21_INFINITE, 2.5));
}
END_TEST

START_TEST(test_s21_fmod_5) {
#line 469
  ck_assert_ldouble_nan(s21_fmod(2.5, S21_ZERO_PLUS));
  ck_assert_ldouble_nan(fmod(2.5, S21_ZERO_PLUS));
}
END_TEST

START_TEST(test_s21_fmod_6) {
#line 472
  ck_assert_ldouble_nan(s21_fmod(2.5, S21_ZERO_MINUS));
  ck_assert_ldouble_nan(fmod(2.5, S21_ZERO_MINUS));
}
END_TEST

START_TEST(test_s21_fmod_7) {
#line 475
  ck_assert_ldouble_eq_tol(fmod(2.5, S21_INFINITE_MINUS),
                           s21_fmod(2.5, S21_INFINITE_MINUS), 0.000001);
}
END_TEST

START_TEST(test_s21_fmod_8) {
#line 477
  ck_assert_ldouble_eq_tol(fmod(2.5, S21_INFINITE), s21_fmod(2.5, S21_INFINITE),
                           0.000001);
}
END_TEST

START_TEST(test_s21_fmod_9) {
#line 479
  ck_assert_ldouble_nan(s21_fmod(S21_NAN, 2.5));
  ck_assert_ldouble_nan(fmod(S21_NAN, 2.5));
}
END_TEST

START_TEST(test_s21_fmod_10) {
#line 482
  ck_assert_ldouble_nan(s21_fmod(2.5, S21_NAN));
  ck_assert_ldouble_nan(fmod(2.5, S21_NAN));
}
END_TEST

START_TEST(test_s21_fmod_11) {
#line 485
  ck_assert_ldouble_nan(s21_fmod(S21_NAN, S21_NAN));
  ck_assert_ldouble_nan(fmod(S21_NAN, S21_NAN));
}
END_TEST
START_TEST(test_s21_log1) {
#line 492
  ck_assert_ldouble_nan(log(-13.54));
  ck_assert_ldouble_nan(s21_log(-13.54));
}
END_TEST

START_TEST(test_s21_log2) {
#line 495
  ck_assert_ldouble_eq_tol(log(13.54), s21_log(13.54), 0.000001);
}
END_TEST

START_TEST(test_s21_log3) {
#line 497
  ck_assert_ldouble_infinite(log(0.0));
  ck_assert_ldouble_infinite(s21_log(0.0));
  ck_assert_ldouble_lt(log(0.0), 0);
  ck_assert_ldouble_lt(s21_log(0.0), 0);
}
END_TEST

START_TEST(test_s21_log4) {
#line 502
  ck_assert_ldouble_eq_tol(log(1.0), s21_log(1.0), 0.000001);
}
END_TEST

START_TEST(test_s21_log5) {
#line 504
  ck_assert_ldouble_eq_tol(log(3.14), s21_log(3.14), 0.000001);
}
END_TEST

START_TEST(test_s21_log6) {
#line 506
  ck_assert_ldouble_eq_tol(log(6.28), s21_log(6.28), 0.000001);
}
END_TEST

START_TEST(test_s21_log7) {
#line 508
  ck_assert_ldouble_eq_tol(log(2.2343), s21_log(2.2343), 0.000001);
}
END_TEST

START_TEST(test_s21_log8) {
#line 510
  ck_assert_ldouble_eq_tol(log(0.1234), s21_log(0.1234), 0.000001);
}
END_TEST

START_TEST(test_s21_log_1) {
#line 512
  ck_assert_ldouble_infinite(log(S21_ZERO_PLUS));
  ck_assert_ldouble_infinite(s21_log(S21_ZERO_PLUS));
  ck_assert_ldouble_lt(log(S21_ZERO_PLUS), 0);
  ck_assert_ldouble_lt(s21_log(S21_ZERO_PLUS), 0);
}
END_TEST

START_TEST(test_s21_log_2) {
#line 517
  ck_assert_ldouble_infinite(log(S21_ZERO_MINUS));
  ck_assert_ldouble_infinite(s21_log(S21_ZERO_MINUS));
  ck_assert_ldouble_lt(log(S21_ZERO_MINUS), 0);
  ck_assert_ldouble_lt(s21_log(S21_ZERO_MINUS), 0);
}
END_TEST

START_TEST(test_s21_log_3) {
#line 522
  ck_assert_ldouble_eq_tol(log(1), s21_log(1), 0.000001);
}
END_TEST

START_TEST(test_s21_log_4) {
#line 524
  ck_assert_ldouble_infinite(log(S21_INFINITE));
  ck_assert_ldouble_infinite(s21_log(S21_INFINITE));
  ck_assert_ldouble_gt(log(S21_INFINITE), 0);
  ck_assert_ldouble_gt(s21_log(S21_INFINITE), 0);
}
END_TEST

START_TEST(test_s21_log_5) {
#line 529
  ck_assert_ldouble_nan(s21_log(-1));
  ck_assert_ldouble_nan(log(-1));
}
END_TEST

START_TEST(test_s21_log_6) {
#line 532
  ck_assert_ldouble_nan(s21_log(S21_INFINITE_MINUS));
  ck_assert_ldouble_nan(log(S21_INFINITE_MINUS));
}
END_TEST

START_TEST(test_s21_log_7) {
#line 535
  ck_assert_ldouble_nan(s21_log(S21_NAN));
  ck_assert_ldouble_nan(log(S21_NAN));
}
END_TEST

START_TEST(test_s21_log6_10) {
#line 538
  ck_assert_ldouble_eq_tol(log(DBL_MAX), s21_log(DBL_MAX), 0.000001);
}
END_TEST

START_TEST(test_s21_log6_12) {
#line 540
  ck_assert_ldouble_nan(log(-DBL_MAX));
  ck_assert_ldouble_nan(s21_log(-DBL_MAX));
}
END_TEST

START_TEST(test_s21_log6_13) {
#line 543
  ck_assert_ldouble_nan(log(-DBL_MIN));
  ck_assert_ldouble_nan(s21_log(-DBL_MIN));
}
END_TEST
START_TEST(test_s21_sin1) {
#line 549
  ck_assert_ldouble_eq_tol(sin(-13.54), s21_sin(-13.54), 0.000001);
}
END_TEST

START_TEST(test_s21_sin2) {
#line 551
  ck_assert_ldouble_eq_tol(sin(13.54), s21_sin(13.54), 0.000001);
}
END_TEST

START_TEST(test_s21_sin3) {
#line 553
  ck_assert_ldouble_eq_tol(sin(0.0), s21_sin(0.0), 0.000001);
}
END_TEST

START_TEST(test_s21_sin4) {
#line 555
  ck_assert_ldouble_eq_tol(sin(1.0), s21_sin(1.0), 0.000001);
}
END_TEST

START_TEST(test_s21_sin5) {
#line 557
  ck_assert_ldouble_eq_tol(sin(2.5), s21_sin(2.5), 0.000001);
}
END_TEST

START_TEST(test_s21_sin6) {
#line 559
  ck_assert_ldouble_eq_tol(sin(6.28), s21_sin(6.28), 0.000001);
}
END_TEST

START_TEST(test_s21_sin7) {
#line 561
  ck_assert_ldouble_eq_tol(sin(2.2343), s21_sin(2.2343), 0.000001);
}
END_TEST

START_TEST(test_s21_sin8) {
#line 563
  ck_assert_ldouble_eq_tol(sin(0.1234), s21_sin(0.1234), 0.000001);
}
END_TEST

START_TEST(test_s21_sin_1) {
#line 565
  ck_assert_ldouble_eq_tol(sin(S21_ZERO_PLUS), s21_sin(S21_ZERO_PLUS),
                           0.000001);
}
END_TEST

START_TEST(test_s21_sin_2) {
#line 567
  ck_assert_ldouble_eq_tol(sin(S21_ZERO_MINUS), s21_sin(S21_ZERO_MINUS),
                           0.000001);
}
END_TEST

START_TEST(test_s21_sin_3) {
#line 569
  ck_assert_ldouble_nan(s21_sin(S21_INFINITE_MINUS));
  ck_assert_ldouble_nan(sin(S21_INFINITE_MINUS));
}
END_TEST

START_TEST(test_s21_sin_4) {
#line 572
  ck_assert_ldouble_nan(s21_sin(S21_INFINITE));
  ck_assert_ldouble_nan(sin(S21_INFINITE));
}
END_TEST

START_TEST(test_s21_sin_5) {
#line 575
  ck_assert_ldouble_nan(s21_sin(S21_NAN));
  ck_assert_ldouble_nan(sin(S21_NAN));
}
END_TEST
START_TEST(test_s21_cos121) {
#line 580
  ck_assert_ldouble_eq_tol(cos(-13.54), s21_cos(-13.54), 0.000001);
}
END_TEST

START_TEST(test_s21_cos222) {
#line 582
  ck_assert_ldouble_eq_tol(cos(13.54), s21_cos(13.54), 0.000001);
}
END_TEST

START_TEST(test_s21_cos3212) {
#line 584
  ck_assert_ldouble_eq_tol(cos(0.0), s21_cos(0.0), 0.000001);
}
END_TEST

START_TEST(test_s21_cos4212) {
#line 586
  ck_assert_ldouble_eq_tol(cos(1.0), s21_cos(1.0), 0.000001);
}
END_TEST

START_TEST(test_s21_cos5212) {
#line 588
  ck_assert_ldouble_eq_tol(cos(3.14), s21_cos(3.14), 0.000001);
}
END_TEST

START_TEST(test_s21_cos6212) {
#line 590
  ck_assert_ldouble_eq_tol(cos(6.28), s21_cos(6.28), 0.000001);
}
END_TEST

START_TEST(test_s21_cos721) {
#line 592
  ck_assert_ldouble_eq_tol(cos(2.2343), s21_cos(2.2343), 0.000001);
}
END_TEST

START_TEST(test_s21_cos8) {
#line 594
  ck_assert_ldouble_eq_tol(cos(0.1234), s21_cos(0.1234), 0.000001);
}
END_TEST

START_TEST(test_s21_cos_1_1) {
#line 596
  ck_assert_ldouble_eq_tol(cos(S21_ZERO_MINUS), s21_cos(S21_ZERO_MINUS),
                           0.000001);
}
END_TEST

START_TEST(test_s21_cos_2_2) {
#line 598
  ck_assert_ldouble_eq_tol(cos(S21_ZERO_PLUS), s21_cos(S21_ZERO_PLUS),
                           0.000001);
}
END_TEST

START_TEST(test_s21_cos_3_3) {
#line 600
  ck_assert_ldouble_nan(s21_cos(S21_INFINITE_MINUS));
  ck_assert_ldouble_nan(cos(S21_INFINITE_MINUS));
}
END_TEST

START_TEST(test_s21_cos_4_4) {
#line 603
  ck_assert_ldouble_nan(s21_cos(S21_INFINITE));
  ck_assert_ldouble_nan(cos(S21_INFINITE));
}
END_TEST

START_TEST(test_s21_cos_5_5) {
#line 606
  ck_assert_ldouble_nan(s21_cos(S21_NAN));
  ck_assert_ldouble_nan(cos(S21_NAN));
}
END_TEST
START_TEST(test_s21_tan1) {
#line 613
  ck_assert_ldouble_eq_tol(tan(-13.54), s21_tan(-13.54), 0.000001);
}
END_TEST

START_TEST(test_s21_tan2) {
#line 615
  ck_assert_ldouble_eq_tol(tan(13.54), s21_tan(13.54), 0.000001);
}
END_TEST

START_TEST(test_s21_tan3) {
#line 617
  ck_assert_ldouble_eq_tol(tan(0), s21_tan(0), 0.000001);
}
END_TEST

START_TEST(test_s21_tan4) {
#line 619
  ck_assert_ldouble_eq_tol(tan(1), s21_tan(1), 0.000001);
}
END_TEST

START_TEST(test_s21_tan5) {
#line 621
  ck_assert_ldouble_eq_tol(tan(2.5), s21_tan(2.5), 0.000001);
}
END_TEST

START_TEST(test_s21_tan6) {
#line 623
  ck_assert_ldouble_eq_tol(tan(6.28), s21_tan(6.28), 0.000001);
}
END_TEST

START_TEST(test_s21_tan7) {
#line 625
  ck_assert_ldouble_eq_tol(tan(2.2343), s21_tan(2.2343), 0.000001);
}
END_TEST

START_TEST(test_s21_tan8) {
#line 627
  ck_assert_ldouble_eq_tol(tan(0.1234), s21_tan(0.1234), 0.000001);
}
END_TEST

START_TEST(test_s21_tan_1) {
#line 629
  ck_assert_ldouble_eq_tol(tan(S21_ZERO_MINUS), s21_tan(S21_ZERO_MINUS),
                           0.000001);
}
END_TEST

START_TEST(test_s21_tan_2) {
#line 631
  ck_assert_ldouble_eq_tol(tan(S21_ZERO_PLUS), s21_tan(S21_ZERO_PLUS),
                           0.000001);
}
END_TEST

START_TEST(test_s21_tan_3) {
#line 633
  ck_assert_ldouble_nan(s21_tan(S21_INFINITE_MINUS));
  ck_assert_ldouble_nan(tan(S21_INFINITE_MINUS));
}
END_TEST

START_TEST(test_s21_tan_4) {
#line 636
  ck_assert_ldouble_nan(s21_tan(S21_INFINITE));
  ck_assert_ldouble_nan(tan(S21_INFINITE));
}
END_TEST

START_TEST(test_s21_tan_5) {
#line 639
  ck_assert_ldouble_nan(s21_tan(S21_NAN));
  ck_assert_ldouble_nan(tan(S21_NAN));
}
END_TEST
START_TEST(test_s21_sqrt1) {
#line 645
  ck_assert_ldouble_eq_tol(sqrt(0.0), s21_sqrt(0.0), 0.000001);
}
END_TEST

START_TEST(test_s21_sqrt2) {
#line 647
  ck_assert_ldouble_eq_tol(sqrt(1.0), s21_sqrt(1.0), 0.000001);
}
END_TEST

START_TEST(test_s21_sqrt3) {
#line 649
  ck_assert_ldouble_eq_tol(sqrt(3.14), s21_sqrt(3.14), 0.000001);
}
END_TEST

START_TEST(test_s21_sqrt4) {
#line 651
  ck_assert_ldouble_eq_tol(sqrt(6.28), s21_sqrt(6.28), 0.000001);
}
END_TEST

START_TEST(test_s21_sqrt5) {
#line 653
  ck_assert_ldouble_eq_tol(sqrt(2.2343), s21_sqrt(2.2343), 0.000001);
}
END_TEST

START_TEST(test_s21_sqrt6) {
#line 655
  ck_assert_ldouble_nan(sqrt(-123));
  ck_assert_ldouble_nan(s21_sqrt(-123));
}
END_TEST

START_TEST(test_s21_sqrt_1) {
#line 658
  ck_assert_ldouble_infinite(sqrt(S21_INFINITE));
  ck_assert_ldouble_infinite(s21_sqrt(S21_INFINITE));
  ck_assert_ldouble_gt(sqrt(S21_INFINITE), 0);
  ck_assert_ldouble_gt(s21_sqrt(S21_INFINITE), 0);
}
END_TEST

START_TEST(test_s21_sqrt_2) {
#line 663
  ck_assert_ldouble_eq_tol(sqrt(S21_ZERO_MINUS), s21_sqrt(S21_ZERO_MINUS),
                           0.000001);
}
END_TEST

START_TEST(test_s21_sqrt_3) {
#line 665
  ck_assert_ldouble_eq_tol(sqrt(S21_ZERO_PLUS), s21_sqrt(S21_ZERO_PLUS),
                           0.000001);
}
END_TEST

START_TEST(test_s21_sqrt_4) {
#line 667
  ck_assert_ldouble_nan(s21_sqrt(-1));
  ck_assert_ldouble_nan(sqrt(-1));
}
END_TEST

START_TEST(test_s21_sqrt_5) {
#line 670
  ck_assert_ldouble_nan(s21_sqrt(S21_NAN));
  ck_assert_ldouble_nan(sqrt(S21_NAN));
}
END_TEST

START_TEST(test_s21_sqrt511) {
#line 673
  ck_assert_ldouble_nan(sqrt(-DBL_MAX));
  ck_assert_ldouble_nan(s21_sqrt(-DBL_MAX));
}
END_TEST

START_TEST(test_s21_sqrt513) {
#line 676
  ck_assert_ldouble_nan(sqrt(-DBL_MIN));
  ck_assert_ldouble_nan(s21_sqrt(-DBL_MIN));
}
END_TEST
START_TEST(test_s21_pow1) {
#line 683
  ck_assert_ldouble_nan(pow(-13.21313, 2.5));
  ck_assert_ldouble_nan(s21_pow(-13.21313, 2.5));
}
END_TEST

START_TEST(test_s21_pow2) {
#line 686
  ck_assert_ldouble_eq_tol(pow(13.21313, 2.5), s21_pow(13.21313, 2.5),
                           0.000001);
}
END_TEST

START_TEST(test_s21_pow3) {
#line 688
  ck_assert_ldouble_nan(pow(-1000.21313, 2.5));
  ck_assert_ldouble_nan(s21_pow(-1000.21313, 2.5));
}
END_TEST

START_TEST(test_s21_pow4) {
#line 691
  ck_assert_ldouble_eq_tol(pow(32346234.21313, 0), s21_pow(32346234.21313, 0),
                           0.000001);
}
END_TEST

START_TEST(test_s21_pow5) {
#line 693
  ck_assert_ldouble_eq_tol(pow(0, 2.5), s21_pow(0, 2.5), 0.000001);
}
END_TEST

START_TEST(test_s21_pow6) {
#line 695
  ck_assert_ldouble_eq_tol(pow(123, -2), s21_pow(123, -2), 0.000001);
}
END_TEST

START_TEST(test_s21_pow_1) {
#line 697
  ck_assert_ldouble_eq_tol(pow(2, 2), s21_pow(2, 2), 0.000001);
}
END_TEST

START_TEST(test_s21_pow_2) {
#line 699
  ck_assert_ldouble_eq_tol(pow(2, 3), s21_pow(2, 3), 0.000001);
}
END_TEST

START_TEST(test_s21_pow_3) {
#line 701
  ck_assert_ldouble_eq_tol(pow(2, 10), s21_pow(2, 10), 0.000001);
}
END_TEST

START_TEST(test_s21_pow_4) {
#line 703
  ck_assert_ldouble_eq_tol(pow(2, 0.5), s21_pow(2, 0.5), 0.000001);
}
END_TEST

START_TEST(test_s21_pow_5) {
#line 705
  ck_assert_ldouble_eq_tol(pow(-2, -3), s21_pow(-2, -3), 0.000001);
}
END_TEST

START_TEST(test_s21_pow_6) {
#line 707
  ck_assert_ldouble_infinite(pow(S21_ZERO_PLUS, -3));
  ck_assert_ldouble_infinite(s21_pow(S21_ZERO_PLUS, -3));
  ck_assert_ldouble_gt(pow(S21_ZERO_PLUS, -3), 0);
  ck_assert_ldouble_gt(s21_pow(S21_ZERO_PLUS, -3), 0);
}
END_TEST

START_TEST(test_s21_pow_7) {
#line 712
  ck_assert_ldouble_infinite(pow(S21_ZERO_MINUS, -5));
  ck_assert_ldouble_infinite(s21_pow(S21_ZERO_MINUS, -5));
  ck_assert_ldouble_lt(pow(S21_ZERO_MINUS, -5), 0);
  ck_assert_ldouble_lt(s21_pow(S21_ZERO_MINUS, -5), 0);
}
END_TEST

START_TEST(test_s21_pow_8) {
#line 717
  ck_assert_ldouble_infinite(pow(S21_ZERO_PLUS, -2));
  ck_assert_ldouble_infinite(s21_pow(S21_ZERO_PLUS, -2));
  ck_assert_ldouble_gt(pow(S21_ZERO_PLUS, -2), 0);
  ck_assert_ldouble_gt(s21_pow(S21_ZERO_PLUS, -2), 0);
}
END_TEST

START_TEST(test_s21_pow_9) {
#line 722
  ck_assert_ldouble_infinite(pow(S21_ZERO_MINUS, -4));
  ck_assert_ldouble_infinite(s21_pow(S21_ZERO_MINUS, -4));
  ck_assert_ldouble_gt(pow(S21_ZERO_MINUS, -4), 0);
  ck_assert_ldouble_gt(s21_pow(S21_ZERO_MINUS, -4), 0);
}
END_TEST

START_TEST(test_s21_pow_8_1) {
#line 727
  ck_assert_ldouble_infinite(pow(S21_ZERO_PLUS, -0.5));
  ck_assert_ldouble_infinite(s21_pow(S21_ZERO_PLUS, -0.5));
  ck_assert_ldouble_gt(pow(S21_ZERO_PLUS, -0.5), 0);
  ck_assert_ldouble_gt(s21_pow(S21_ZERO_PLUS, -0.5), 0);
}
END_TEST

START_TEST(test_s21_pow_9_2) {
#line 732
  ck_assert_ldouble_infinite(pow(S21_ZERO_MINUS, -1.5));
  ck_assert_ldouble_infinite(s21_pow(S21_ZERO_MINUS, -1.5));
  ck_assert_ldouble_gt(pow(S21_ZERO_MINUS, -1.5), 0);
  ck_assert_ldouble_gt(s21_pow(S21_ZERO_MINUS, -1.5), 0);
}
END_TEST

START_TEST(test_s21_pow_10) {
#line 737
  ck_assert_ldouble_infinite(pow(S21_ZERO_MINUS, S21_INFINITE_MINUS));
  ck_assert_ldouble_infinite(s21_pow(S21_ZERO_MINUS, S21_INFINITE_MINUS));
  ck_assert_ldouble_gt(pow(S21_ZERO_MINUS, S21_INFINITE_MINUS), 0);
  ck_assert_ldouble_gt(s21_pow(S21_ZERO_MINUS, S21_INFINITE_MINUS), 0);
}
END_TEST

START_TEST(test_s21_pow_10_1) {
#line 742
  ck_assert_ldouble_infinite(pow(S21_ZERO_PLUS, S21_INFINITE_MINUS));
  ck_assert_ldouble_infinite(s21_pow(S21_ZERO_PLUS, S21_INFINITE_MINUS));
  ck_assert_ldouble_gt(pow(S21_ZERO_PLUS, S21_INFINITE_MINUS), 0);
  ck_assert_ldouble_gt(s21_pow(S21_ZERO_PLUS, S21_INFINITE_MINUS), 0);
}
END_TEST

START_TEST(test_s21_pow_11) {
#line 747
  ck_assert_ldouble_eq_tol(pow(S21_ZERO_PLUS, 3), s21_pow(S21_ZERO_PLUS, 3),
                           0.000001);
}
END_TEST

START_TEST(test_s21_pow_12) {
#line 749
  ck_assert_ldouble_eq_tol(pow(S21_ZERO_MINUS, 5), s21_pow(S21_ZERO_MINUS, 5),
                           0.000001);
}
END_TEST

START_TEST(test_s21_pow_13) {
#line 751
  ck_assert_ldouble_eq_tol(pow(S21_ZERO_MINUS, 2), s21_pow(S21_ZERO_MINUS, 2),
                           0.000001);
}
END_TEST

START_TEST(test_s21_pow_14) {
#line 753
  ck_assert_ldouble_eq_tol(pow(S21_ZERO_PLUS, 4), s21_pow(S21_ZERO_PLUS, 4),
                           0.000001);
}
END_TEST

START_TEST(test_s21_pow_13_1) {
#line 755
  ck_assert_ldouble_eq_tol(pow(S21_ZERO_MINUS, 2), s21_pow(S21_ZERO_MINUS, 2.5),
                           0.000001);
}
END_TEST

START_TEST(test_s21_pow_14_1) {
#line 757
  ck_assert_ldouble_eq_tol(pow(S21_ZERO_PLUS, 4), s21_pow(S21_ZERO_PLUS, 4.5),
                           0.000001);
}
END_TEST

START_TEST(test_s21_pow_15) {
#line 759
  ck_assert_ldouble_eq_tol(pow(-1, S21_INFINITE), s21_pow(-1, S21_INFINITE),
                           0.000001);
}
END_TEST

START_TEST(test_s21_pow_16) {
#line 761
  ck_assert_ldouble_eq_tol(pow(-1, S21_INFINITE_MINUS),
                           s21_pow(-1, S21_INFINITE_MINUS), 0.000001);
}
END_TEST

START_TEST(test_s21_pow_17) {
#line 763
  ck_assert_ldouble_eq_tol(pow(1, S21_NAN), s21_pow(1, S21_NAN), 0.000001);
}
END_TEST

START_TEST(test_s21_pow_17_1) {
#line 765
  ck_assert_ldouble_eq_tol(pow(1, 3), s21_pow(1, 3), 0.000001);
}
END_TEST

START_TEST(test_s21_pow_18) {
#line 767
  ck_assert_ldouble_eq_tol(pow(S21_NAN, S21_ZERO_PLUS),
                           s21_pow(S21_NAN, S21_ZERO_PLUS), 0.000001);
}
END_TEST

START_TEST(test_s21_pow_18_1) {
#line 769
  ck_assert_ldouble_eq_tol(pow(S21_NAN, S21_ZERO_MINUS),
                           s21_pow(S21_NAN, S21_ZERO_MINUS), 0.000001);
}
END_TEST

START_TEST(test_s21_pow_18_2) {
#line 771
  ck_assert_ldouble_eq_tol(pow(4, S21_ZERO_MINUS), s21_pow(4, S21_ZERO_MINUS),
                           0.000001);
}
END_TEST

START_TEST(test_s21_pow_19) {
#line 773
  ck_assert_ldouble_nan(s21_pow(-5, 0.4));
  ck_assert_ldouble_nan(pow(-5, 0.4));
}
END_TEST

START_TEST(test_s21_pow_19_1) {
#line 776
  ck_assert_ldouble_nan(s21_pow(-5, 0.4));
  ck_assert_ldouble_nan(pow(-5, 0.4));
}
END_TEST

START_TEST(test_s21_pow_20) {
#line 779
  ck_assert_ldouble_infinite(pow(0.4, S21_INFINITE_MINUS));
  ck_assert_ldouble_infinite(s21_pow(0.4, S21_INFINITE_MINUS));
  ck_assert_ldouble_gt(pow(0.4, S21_INFINITE_MINUS), 0);
  ck_assert_ldouble_gt(s21_pow(0.4, S21_INFINITE_MINUS), 0);
}
END_TEST

START_TEST(test_s21_pow_20_1) {
#line 784
  ck_assert_ldouble_infinite(pow(-0.04, S21_INFINITE_MINUS));
  ck_assert_ldouble_infinite(s21_pow(0.4, S21_INFINITE_MINUS));
  ck_assert_ldouble_gt(pow(-0.04, S21_INFINITE_MINUS), 0);
  ck_assert_ldouble_gt(s21_pow(0.4, S21_INFINITE_MINUS), 0);
}
END_TEST

START_TEST(test_s21_pow_21) {
#line 789
  ck_assert_ldouble_eq_tol(pow(123, S21_INFINITE_MINUS),
                           s21_pow(123, S21_INFINITE_MINUS), 0.000001);
}
END_TEST

START_TEST(test_s21_pow_21_1) {
#line 791
  ck_assert_ldouble_eq_tol(pow(-123, S21_INFINITE_MINUS),
                           s21_pow(-123, S21_INFINITE_MINUS), 0.000001);
}
END_TEST

START_TEST(test_s21_pow_22) {
#line 793
  ck_assert_ldouble_eq_tol(pow(0.3, S21_INFINITE), s21_pow(0.3, S21_INFINITE),
                           0.000001);
}
END_TEST

START_TEST(test_s21_pow_22_1) {
#line 795
  ck_assert_ldouble_eq_tol(pow(-0.3, S21_INFINITE), s21_pow(-0.3, S21_INFINITE),
                           0.000001);
}
END_TEST

START_TEST(test_s21_pow_23) {
#line 797
  ck_assert_ldouble_infinite(pow(123, S21_INFINITE));
  ck_assert_ldouble_infinite(s21_pow(123, S21_INFINITE));
  ck_assert_ldouble_gt(pow(123, S21_INFINITE), 0);
  ck_assert_ldouble_gt(s21_pow(123, S21_INFINITE), 0);
}
END_TEST

START_TEST(test_s21_pow_23_1) {
#line 802
  ck_assert_ldouble_infinite(pow(-123, S21_INFINITE));
  ck_assert_ldouble_infinite(s21_pow(-123, S21_INFINITE));
  ck_assert_ldouble_gt(pow(-123, S21_INFINITE), 0);
  ck_assert_ldouble_gt(s21_pow(-123, S21_INFINITE), 0);
}
END_TEST

START_TEST(test_s21_pow_24) {
#line 807
  ck_assert_ldouble_eq_tol(pow(S21_INFINITE_MINUS, -5),
                           s21_pow(S21_INFINITE_MINUS, -5), 0.000001);
}
END_TEST

START_TEST(test_s21_pow_25) {
#line 809
  ck_assert_ldouble_eq_tol(pow(S21_INFINITE_MINUS, -2.3),
                           s21_pow(S21_INFINITE_MINUS, -2.3), 0.000001);
}
END_TEST

START_TEST(test_s21_pow_26) {
#line 811
  ck_assert_ldouble_eq_tol(pow(S21_INFINITE_MINUS, -2),
                           s21_pow(S21_INFINITE_MINUS, -2), 0.000001);
}
END_TEST

START_TEST(test_s21_pow_27) {
#line 813
  ck_assert_ldouble_infinite(pow(S21_INFINITE_MINUS, 7));
  ck_assert_ldouble_infinite(s21_pow(S21_INFINITE_MINUS, 7));
  ck_assert_ldouble_lt(pow(S21_INFINITE_MINUS, 7), 0);
  ck_assert_ldouble_lt(s21_pow(S21_INFINITE_MINUS, 7), 0);
}
END_TEST

START_TEST(test_s21_pow_28) {
#line 818
  ck_assert_ldouble_infinite(pow(S21_INFINITE_MINUS, 4.6));
  ck_assert_ldouble_infinite(s21_pow(S21_INFINITE_MINUS, 4.6));
  ck_assert_ldouble_gt(pow(S21_INFINITE_MINUS, 4.6), 0);
  ck_assert_ldouble_gt(s21_pow(S21_INFINITE_MINUS, 4.6), 0);
}
END_TEST

START_TEST(test_s21_pow_29) {
#line 823
  ck_assert_ldouble_infinite(pow(S21_INFINITE_MINUS, 10));
  ck_assert_ldouble_infinite(s21_pow(S21_INFINITE_MINUS, 10));
  ck_assert_ldouble_gt(pow(S21_INFINITE_MINUS, 10), 0);
  ck_assert_ldouble_gt(s21_pow(S21_INFINITE_MINUS, 10), 0);
}
END_TEST

START_TEST(test_s21_pow_30) {
#line 828
  ck_assert_ldouble_eq_tol(pow(S21_INFINITE, -14), s21_pow(S21_INFINITE, -14),
                           0.000001);
}
END_TEST

START_TEST(test_s21_pow_31) {
#line 830
  ck_assert_ldouble_infinite(s21_pow(S21_INFINITE, 48));
  ck_assert_ldouble_infinite(pow(S21_INFINITE, 48));
  ck_assert_ldouble_gt(pow(S21_INFINITE, 48), 0);
  ck_assert_ldouble_gt(s21_pow(S21_INFINITE, 48), 0);
}
END_TEST

START_TEST(test_s21_pow_32) {
#line 835
  ck_assert_ldouble_nan(s21_pow(S21_NAN, -2));
  ck_assert_ldouble_nan(pow(S21_NAN, -2));
}
END_TEST

START_TEST(test_s21_pow_33) {
#line 838
  ck_assert_ldouble_nan(s21_pow(123, S21_NAN));
  ck_assert_ldouble_nan(pow(123, S21_NAN));
}
END_TEST

START_TEST(test_s21_pow_34) {
#line 841
  ck_assert_ldouble_nan(s21_pow(S21_NAN, S21_NAN));
  ck_assert_ldouble_nan(pow(S21_NAN, S21_NAN));
}
END_TEST

START_TEST(test_s21_pow_35) {
#line 844
  ck_assert_ldouble_eq_tol(s21_pow(S21_ZERO_PLUS, S21_ZERO_PLUS),
                           pow(S21_ZERO_PLUS, S21_ZERO_PLUS), 0.000001);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("test_s21_abs");
  TCase *tc1_1 = tcase_create("test_s21_abs");
  Suite *s2 = suite_create("test_s21_fabs");
  TCase *tc2_1 = tcase_create("test_s21_fabs");
  Suite *s3 = suite_create("test_s21_acos");
  TCase *tc3_1 = tcase_create("test_s21_acos");
  Suite *s4 = suite_create("test_s21_asin");
  TCase *tc4_1 = tcase_create("test_s21_asin");
  Suite *s5 = suite_create("test_s21_atan");
  TCase *tc5_1 = tcase_create("test_s21_atan");
  Suite *s6 = suite_create("test_s21_ceil");
  TCase *tc6_1 = tcase_create("test_s21_ceil");
  Suite *s7 = suite_create("test_s21_cos");
  TCase *tc7_1 = tcase_create("test_s21_cos");
  Suite *s8 = suite_create("test_s21_exp");
  TCase *tc8_1 = tcase_create("test_s21_exp");
  Suite *s9 = suite_create("test_s21_floor");
  TCase *tc9_1 = tcase_create("test_s21_floor");
  Suite *s10 = suite_create("test_s21_fmod");
  TCase *tc10_1 = tcase_create("test_s21_fmod");
  Suite *s11 = suite_create("test_s21_log");
  TCase *tc11_1 = tcase_create("test_s21_log");
  Suite *s12 = suite_create("test_s21_sin");
  TCase *tc12_1 = tcase_create("test_s21_sin");
  Suite *s13 = suite_create("test_s21_cos12");
  TCase *tc13_1 = tcase_create("test_s21_cos12");
  Suite *s14 = suite_create("test_s21_tan");
  TCase *tc14_1 = tcase_create("test_s21_tan");
  Suite *s15 = suite_create("test_s21_sqrt");
  TCase *tc15_1 = tcase_create("test_s21_sqrt");
  Suite *s16 = suite_create("test_s21_pow");
  TCase *tc16_1 = tcase_create("test_s21_pow");
  SRunner *sr = srunner_create(s1);
  int nf;

  /* User-specified pre-run code */
#line 847
  srunner_set_fork_status(sr, CK_NOFORK);

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, test_s21_abs_positive);
  tcase_add_test(tc1_1, test_s21_abs_negative);
  tcase_add_test(tc1_1, test_s21_abs_zero);
  tcase_add_test(tc1_1, test_s21_abs_border);
  tcase_add_test(tc1_1, test_s21_abs_border2);
  tcase_add_test(tc1_1, test_s21_abs_border3);
  tcase_add_test(tc1_1, test_s21_abs_border4);
  tcase_add_test(tc1_1, test_s21_abs_border5);
  tcase_add_test(tc1_1, test_s21_abs_border6);
  tcase_add_test(tc1_1, test_s21_abs_border61);
  tcase_add_test(tc1_1, test_s21_abs_border62);
  tcase_add_test(tc1_1, test_s21_abs_border63);
  tcase_add_test(tc1_1, test_s21_abs_border64);
  tcase_add_test(tc1_1, test_s21_abs_border65);
  tcase_add_test(tc1_1, test_s21_abs_border66);
  tcase_add_test(tc1_1, test_s21_abs_border67);
  tcase_add_test(tc1_1, test_s21_abs_border68);
  tcase_add_test(tc1_1, test_s21_abs_border69);
  suite_add_tcase(s2, tc2_1);
  tcase_add_test(tc2_1, test_s21_fabs_positive);
  tcase_add_test(tc2_1, test_s21_fabs_negative);
  tcase_add_test(tc2_1, test_s21_fabs_zero);
  tcase_add_test(tc2_1, test_s21_fabs_zero_minus);
  tcase_add_test(tc2_1, test_s21_fabs_inf_minus);
  tcase_add_test(tc2_1, test_s21_fabs_inf_plus);
  tcase_add_test(tc2_1, test_s21_fabs_max_positive);
  tcase_add_test(tc2_1, test_s21_fabs_max_negative);
  tcase_add_test(tc2_1, test_s21_fabs_min_positive);
  tcase_add_test(tc2_1, test_s21_fabs_min_negative);
  tcase_add_test(tc2_1, test_s21_fabs_border);
  tcase_add_test(tc2_1, test_s21_fabs_border2);
  tcase_add_test(tc2_1, test_s21_fabs_border3);
  tcase_add_test(tc2_1, test_s21_fabs_border4);
  tcase_add_test(tc2_1, test_s21_fabs_border5);
  tcase_add_test(tc2_1, test_s21_fabs_border6);
  tcase_add_test(tc2_1, test_s21_fabs_border7);
  tcase_add_test(tc2_1, test_s21_fabs_border8);
  tcase_add_test(tc2_1, test_s21_fabs_border9);
  suite_add_tcase(s3, tc3_1);
  tcase_add_test(tc3_1, test_s21_acos_positive);
  tcase_add_test(tc3_1, test_s21_acos_negative);
  tcase_add_test(tc3_1, test_s21_acos_border);
  tcase_add_test(tc3_1, test_s21_acos_border2);
  tcase_add_test(tc3_1, test_s21_acos_border3);
  tcase_add_test(tc3_1, test_s21_acos_border4);
  tcase_add_test(tc3_1, test_s21_acos_border5);
  tcase_add_test(tc3_1, test_s21_acos_border6);
  tcase_add_test(tc3_1, test_s21_acos_border7);
  tcase_add_test(tc3_1, test_s21_acos_border8);
  tcase_add_test(tc3_1, test_s21_acos_border9);
  tcase_add_test(tc3_1, test_s21_acos_border10);
  tcase_add_test(tc3_1, test_s21_acos_border11);
  tcase_add_test(tc3_1, test_s21_acos_border12);
  tcase_add_test(tc3_1, test_s21_acos_border13);
  tcase_add_test(tc3_1, test_s21_acos_border14);
  tcase_add_test(tc3_1, test_s21_acos_border110);
  tcase_add_test(tc3_1, test_s21_acos_border111);
  tcase_add_test(tc3_1, test_s21_acos_border112);
  tcase_add_test(tc3_1, test_s21_acos_border113);
  suite_add_tcase(s4, tc4_1);
  tcase_add_test(tc4_1, test_s21_asin_positive);
  tcase_add_test(tc4_1, test_s21_asin_negative);
  tcase_add_test(tc4_1, test_s21_asin_bound);
  tcase_add_test(tc4_1, test_s21_asin_bound2);
  tcase_add_test(tc4_1, test_s21_asin_bound3);
  tcase_add_test(tc4_1, test_s21_asin_bound4);
  tcase_add_test(tc4_1, test_s21_asin_bound5);
  tcase_add_test(tc4_1, test_s21_asin_bound6);
  tcase_add_test(tc4_1, test_s21_asin_bound7);
  tcase_add_test(tc4_1, test_s21_asin_bound8);
  tcase_add_test(tc4_1, test_s21_asin_bound9);
  tcase_add_test(tc4_1, test_s21_asin_bound10);
  tcase_add_test(tc4_1, test_s21_asin_bound11);
  tcase_add_test(tc4_1, test_s21_asin_bound12);
  suite_add_tcase(s5, tc5_1);
  tcase_add_test(tc5_1, test_s21_atan_positive);
  tcase_add_test(tc5_1, test_s21_atan_zero);
  tcase_add_test(tc5_1, test_s21_atan_zero_minus);
  tcase_add_test(tc5_1, test_s21_atan_negative);
  tcase_add_test(tc5_1, test_s21_atan_positive2);
  tcase_add_test(tc5_1, test_s21_atan_border);
  tcase_add_test(tc5_1, test_s21_atan_border2);
  tcase_add_test(tc5_1, test_s21_atan_border3);
  tcase_add_test(tc5_1, test_s21_atan_border4);
  tcase_add_test(tc5_1, test_s21_atan_border5);
  tcase_add_test(tc5_1, test_s21_atan_border6);
  tcase_add_test(tc5_1, test_s21_atan_border7);
  suite_add_tcase(s6, tc6_1);
  tcase_add_test(tc6_1, test_s21_ceil_positive);
  tcase_add_test(tc6_1, test_s21_ceil_negative);
  tcase_add_test(tc6_1, test_s21_ceil_zero);
  tcase_add_test(tc6_1, test_s21_ceil_1);
  tcase_add_test(tc6_1, test_s21_ceil_2);
  tcase_add_test(tc6_1, test_s21_ceil_3);
  tcase_add_test(tc6_1, test_s21_ceil_4);
  tcase_add_test(tc6_1, test_s21_ceil_5);
  tcase_add_test(tc6_1, test_s21_ceil_6);
  tcase_add_test(tc6_1, test_s21_ceil_7);
  tcase_add_test(tc6_1, test_s21_ceil_8);
  tcase_add_test(tc6_1, test_s21_ceil_9);
  tcase_add_test(tc6_1, test_s21_ceil_10);
  tcase_add_test(tc6_1, test_s21_ceil_11);
  tcase_add_test(tc6_1, test_s21_ceil_12);
  tcase_add_test(tc6_1, test_s21_ceil_13);
  tcase_add_test(tc6_1, test_s21_ceil_14);
  tcase_add_test(tc6_1, test_s21_ceil_15);
  suite_add_tcase(s7, tc7_1);
  tcase_add_test(tc7_1, test_s21_cos_zero);
  tcase_add_test(tc7_1, test_s21_cos_positive);
  tcase_add_test(tc7_1, test_s21_cos_negative);
  tcase_add_test(tc7_1, test_s21_cos_pi);
  tcase_add_test(tc7_1, test_s21_cos_1);
  tcase_add_test(tc7_1, test_s21_cos_2);
  tcase_add_test(tc7_1, test_s21_cos_3);
  tcase_add_test(tc7_1, test_s21_cos_4);
  tcase_add_test(tc7_1, test_s21_cos_5);
  suite_add_tcase(s8, tc8_1);
  tcase_add_test(tc8_1, test_s21_exp_1);
  tcase_add_test(tc8_1, test_s21_exp_2);
  tcase_add_test(tc8_1, test_s21_exp_3);
  tcase_add_test(tc8_1, test_s21_exp_4);
  tcase_add_test(tc8_1, test_s21_exp_5);
  tcase_add_test(tc8_1, test_s21_exp_neg);
  tcase_add_test(tc8_1, test_s21_exp_zero);
  tcase_add_test(tc8_1, test_s21_exp_1_1);
  tcase_add_test(tc8_1, test_s21_exp_2_2);
  tcase_add_test(tc8_1, test_s21_exp_3_3);
  tcase_add_test(tc8_1, test_s21_exp_4_4);
  tcase_add_test(tc8_1, test_s21_exp_5_5);
  tcase_add_test(tc8_1, test_s21_exp_3_10);
  tcase_add_test(tc8_1, test_s21_exp_3_11);
  suite_add_tcase(s9, tc9_1);
  tcase_add_test(tc9_1, test_s21_floor1);
  tcase_add_test(tc9_1, test_s21_floor2);
  tcase_add_test(tc9_1, test_s21_floor3);
  tcase_add_test(tc9_1, test_s21_floor4);
  tcase_add_test(tc9_1, test_s21_floor5);
  tcase_add_test(tc9_1, test_s21_floor6);
  tcase_add_test(tc9_1, test_s21_floor7);
  tcase_add_test(tc9_1, test_s21_floor_1);
  tcase_add_test(tc9_1, test_s21_floor_2);
  tcase_add_test(tc9_1, test_s21_floor_3);
  tcase_add_test(tc9_1, test_s21_floor_4);
  tcase_add_test(tc9_1, test_s21_floor_5);
  tcase_add_test(tc9_1, test_s21_floor70);
  tcase_add_test(tc9_1, test_s21_floor71);
  tcase_add_test(tc9_1, test_s21_floor72);
  tcase_add_test(tc9_1, test_s21_floor73);
  tcase_add_test(tc9_1, test_s21_floor74);
  tcase_add_test(tc9_1, test_s21_floor75);
  tcase_add_test(tc9_1, test_s21_floor76);
  tcase_add_test(tc9_1, test_s21_floor77);
  tcase_add_test(tc9_1, test_s21_floor78);
  tcase_add_test(tc9_1, test_s21_floor79);
  suite_add_tcase(s10, tc10_1);
  tcase_add_test(tc10_1, test_s21_fmod1);
  tcase_add_test(tc10_1, test_s21_fmod2);
  tcase_add_test(tc10_1, test_s21_fmod3);
  tcase_add_test(tc10_1, test_s21_fmod4);
  tcase_add_test(tc10_1, test_s21_fmod5);
  tcase_add_test(tc10_1, test_s21_fmod6);
  tcase_add_test(tc10_1, test_s21_fmod_1);
  tcase_add_test(tc10_1, test_s21_fmod_2);
  tcase_add_test(tc10_1, test_s21_fmod_3);
  tcase_add_test(tc10_1, test_s21_fmod_4);
  tcase_add_test(tc10_1, test_s21_fmod_5);
  tcase_add_test(tc10_1, test_s21_fmod_6);
  tcase_add_test(tc10_1, test_s21_fmod_7);
  tcase_add_test(tc10_1, test_s21_fmod_8);
  tcase_add_test(tc10_1, test_s21_fmod_9);
  tcase_add_test(tc10_1, test_s21_fmod_10);
  tcase_add_test(tc10_1, test_s21_fmod_11);
  suite_add_tcase(s11, tc11_1);
  tcase_add_test(tc11_1, test_s21_log1);
  tcase_add_test(tc11_1, test_s21_log2);
  tcase_add_test(tc11_1, test_s21_log3);
  tcase_add_test(tc11_1, test_s21_log4);
  tcase_add_test(tc11_1, test_s21_log5);
  tcase_add_test(tc11_1, test_s21_log6);
  tcase_add_test(tc11_1, test_s21_log7);
  tcase_add_test(tc11_1, test_s21_log8);
  tcase_add_test(tc11_1, test_s21_log_1);
  tcase_add_test(tc11_1, test_s21_log_2);
  tcase_add_test(tc11_1, test_s21_log_3);
  tcase_add_test(tc11_1, test_s21_log_4);
  tcase_add_test(tc11_1, test_s21_log_5);
  tcase_add_test(tc11_1, test_s21_log_6);
  tcase_add_test(tc11_1, test_s21_log_7);
  tcase_add_test(tc11_1, test_s21_log6_10);
  tcase_add_test(tc11_1, test_s21_log6_12);
  tcase_add_test(tc11_1, test_s21_log6_13);
  suite_add_tcase(s12, tc12_1);
  tcase_add_test(tc12_1, test_s21_sin1);
  tcase_add_test(tc12_1, test_s21_sin2);
  tcase_add_test(tc12_1, test_s21_sin3);
  tcase_add_test(tc12_1, test_s21_sin4);
  tcase_add_test(tc12_1, test_s21_sin5);
  tcase_add_test(tc12_1, test_s21_sin6);
  tcase_add_test(tc12_1, test_s21_sin7);
  tcase_add_test(tc12_1, test_s21_sin8);
  tcase_add_test(tc12_1, test_s21_sin_1);
  tcase_add_test(tc12_1, test_s21_sin_2);
  tcase_add_test(tc12_1, test_s21_sin_3);
  tcase_add_test(tc12_1, test_s21_sin_4);
  tcase_add_test(tc12_1, test_s21_sin_5);
  suite_add_tcase(s13, tc13_1);
  tcase_add_test(tc13_1, test_s21_cos121);
  tcase_add_test(tc13_1, test_s21_cos222);
  tcase_add_test(tc13_1, test_s21_cos3212);
  tcase_add_test(tc13_1, test_s21_cos4212);
  tcase_add_test(tc13_1, test_s21_cos5212);
  tcase_add_test(tc13_1, test_s21_cos6212);
  tcase_add_test(tc13_1, test_s21_cos721);
  tcase_add_test(tc13_1, test_s21_cos8);
  tcase_add_test(tc13_1, test_s21_cos_1_1);
  tcase_add_test(tc13_1, test_s21_cos_2_2);
  tcase_add_test(tc13_1, test_s21_cos_3_3);
  tcase_add_test(tc13_1, test_s21_cos_4_4);
  tcase_add_test(tc13_1, test_s21_cos_5_5);
  suite_add_tcase(s14, tc14_1);
  tcase_add_test(tc14_1, test_s21_tan1);
  tcase_add_test(tc14_1, test_s21_tan2);
  tcase_add_test(tc14_1, test_s21_tan3);
  tcase_add_test(tc14_1, test_s21_tan4);
  tcase_add_test(tc14_1, test_s21_tan5);
  tcase_add_test(tc14_1, test_s21_tan6);
  tcase_add_test(tc14_1, test_s21_tan7);
  tcase_add_test(tc14_1, test_s21_tan8);
  tcase_add_test(tc14_1, test_s21_tan_1);
  tcase_add_test(tc14_1, test_s21_tan_2);
  tcase_add_test(tc14_1, test_s21_tan_3);
  tcase_add_test(tc14_1, test_s21_tan_4);
  tcase_add_test(tc14_1, test_s21_tan_5);
  suite_add_tcase(s15, tc15_1);
  tcase_add_test(tc15_1, test_s21_sqrt1);
  tcase_add_test(tc15_1, test_s21_sqrt2);
  tcase_add_test(tc15_1, test_s21_sqrt3);
  tcase_add_test(tc15_1, test_s21_sqrt4);
  tcase_add_test(tc15_1, test_s21_sqrt5);
  tcase_add_test(tc15_1, test_s21_sqrt6);
  tcase_add_test(tc15_1, test_s21_sqrt_1);
  tcase_add_test(tc15_1, test_s21_sqrt_2);
  tcase_add_test(tc15_1, test_s21_sqrt_3);
  tcase_add_test(tc15_1, test_s21_sqrt_4);
  tcase_add_test(tc15_1, test_s21_sqrt_5);
  tcase_add_test(tc15_1, test_s21_sqrt511);
  tcase_add_test(tc15_1, test_s21_sqrt513);
  suite_add_tcase(s16, tc16_1);
  tcase_add_test(tc16_1, test_s21_pow1);
  tcase_add_test(tc16_1, test_s21_pow2);
  tcase_add_test(tc16_1, test_s21_pow3);
  tcase_add_test(tc16_1, test_s21_pow4);
  tcase_add_test(tc16_1, test_s21_pow5);
  tcase_add_test(tc16_1, test_s21_pow6);
  tcase_add_test(tc16_1, test_s21_pow_1);
  tcase_add_test(tc16_1, test_s21_pow_2);
  tcase_add_test(tc16_1, test_s21_pow_3);
  tcase_add_test(tc16_1, test_s21_pow_4);
  tcase_add_test(tc16_1, test_s21_pow_5);
  tcase_add_test(tc16_1, test_s21_pow_6);
  tcase_add_test(tc16_1, test_s21_pow_7);
  tcase_add_test(tc16_1, test_s21_pow_8);
  tcase_add_test(tc16_1, test_s21_pow_9);
  tcase_add_test(tc16_1, test_s21_pow_8_1);
  tcase_add_test(tc16_1, test_s21_pow_9_2);
  tcase_add_test(tc16_1, test_s21_pow_10);
  tcase_add_test(tc16_1, test_s21_pow_10_1);
  tcase_add_test(tc16_1, test_s21_pow_11);
  tcase_add_test(tc16_1, test_s21_pow_12);
  tcase_add_test(tc16_1, test_s21_pow_13);
  tcase_add_test(tc16_1, test_s21_pow_14);
  tcase_add_test(tc16_1, test_s21_pow_13_1);
  tcase_add_test(tc16_1, test_s21_pow_14_1);
  tcase_add_test(tc16_1, test_s21_pow_15);
  tcase_add_test(tc16_1, test_s21_pow_16);
  tcase_add_test(tc16_1, test_s21_pow_17);
  tcase_add_test(tc16_1, test_s21_pow_17_1);
  tcase_add_test(tc16_1, test_s21_pow_18);
  tcase_add_test(tc16_1, test_s21_pow_18_1);
  tcase_add_test(tc16_1, test_s21_pow_18_2);
  tcase_add_test(tc16_1, test_s21_pow_19);
  tcase_add_test(tc16_1, test_s21_pow_19_1);
  tcase_add_test(tc16_1, test_s21_pow_20);
  tcase_add_test(tc16_1, test_s21_pow_20_1);
  tcase_add_test(tc16_1, test_s21_pow_21);
  tcase_add_test(tc16_1, test_s21_pow_21_1);
  tcase_add_test(tc16_1, test_s21_pow_22);
  tcase_add_test(tc16_1, test_s21_pow_22_1);
  tcase_add_test(tc16_1, test_s21_pow_23);
  tcase_add_test(tc16_1, test_s21_pow_23_1);
  tcase_add_test(tc16_1, test_s21_pow_24);
  tcase_add_test(tc16_1, test_s21_pow_25);
  tcase_add_test(tc16_1, test_s21_pow_26);
  tcase_add_test(tc16_1, test_s21_pow_27);
  tcase_add_test(tc16_1, test_s21_pow_28);
  tcase_add_test(tc16_1, test_s21_pow_29);
  tcase_add_test(tc16_1, test_s21_pow_30);
  tcase_add_test(tc16_1, test_s21_pow_31);
  tcase_add_test(tc16_1, test_s21_pow_32);
  tcase_add_test(tc16_1, test_s21_pow_33);
  tcase_add_test(tc16_1, test_s21_pow_34);
  tcase_add_test(tc16_1, test_s21_pow_35);

  srunner_add_suite(sr, s2);
  srunner_add_suite(sr, s3);
  srunner_add_suite(sr, s4);
  srunner_add_suite(sr, s5);
  srunner_add_suite(sr, s6);
  srunner_add_suite(sr, s7);
  srunner_add_suite(sr, s8);
  srunner_add_suite(sr, s9);
  srunner_add_suite(sr, s10);
  srunner_add_suite(sr, s11);
  srunner_add_suite(sr, s12);
  srunner_add_suite(sr, s13);
  srunner_add_suite(sr, s14);
  srunner_add_suite(sr, s15);
  srunner_add_suite(sr, s16);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
